### PR TITLE
feat(patch): add cmake code to define API_VERSION used when generate …

### PR DESCRIPTION
**Pull request by ledocc**
…mpg123.h

mpg123.h.in require API_VERSION variable to be defined. So read value from configure.ac and store it in API_VERSION.

### CODE REVIEW

**Comment by Croydon** [comment]
Where is this patch coming from? upstream?

**Comment by ledocc** [comment]
I did It.

**Comment by Croydon** [comment]
Could you please suggest this patch upstream?

**Comment by ledocc** [comment]
done here <https://sourceforge.net/p/mpg123/bugs/287/>

**Comment by Croydon** [comment]
Thanks!

**Pull request merged**
